### ISSUE TITLE
[Bug]: 非常奇怪的报错，

### ISSUE THREAD

**Issue by O5-7** [QwenLM/Qwen3#1499]
### Model Series

Qwen3

### What are the models used?

Qwen3

### What is the scenario where the problem happened?

使用原生torch进行训练和推理

### Is this a known issue?

- [x] I have followed [the GitHub README](https://github.com/QwenLM/Qwen3).
- [x] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [x] I have checked the documentation of the related framework and cannot find useful information.
- [x] I have searched [the issues](https://github.com/QwenLM/Qwen3/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

python 3.12
显卡 : RTX5080 单张
CUDA Version: 12.9
torch==2.7.0+cu128
transformers==4.51.3

### Log output

```shell
2.7.0+cu128
4.51.3
C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cuda\TensorCompare.cu:112: block: [0,0,0], thread: [0,0,0] Assertion `input[0] != 0` failed.
Traceback (most recent call last):
  File "D:\PycharmProjects\Qwen3\bug_report.py", line 48, in <module>
    output_ids = model.generate(**inputs, max_new_tokens=120)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\transformers\generation\utils.py", line 2465, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "D:\anaconda3\Lib\site-packages\transformers\generation\utils.py", line 3476, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

#### Steps to reproduce

This happens to Qwen3-0.6B and Qwen3-1.7B（其余未测试）.
The problem can be reproduced with the following steps:

运行以下代码

```python
import warnings

import transformers

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", message="Failed to load image Python extension.*")

import torch

from transformers import AutoModelForCausalLM, AutoTokenizer, get_scheduler
from transformers.models.qwen2.tokenization_qwen2_fast import Qwen2TokenizerFast
from transformers.models.qwen3.modeling_qwen3 import Qwen3ForCausalLM

from torch.optim import Adam
import os


if __name__ == '__main__':
    print(torch.__version__)
    print(transformers.__version__)

    os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
    model_name = "../dl_models/Qwen3-0.6B" # local
    device = "cuda" if torch.cuda.is_available() else "cpu"

    tokenizer: Qwen2TokenizerFast = AutoTokenizer.from_pretrained(model_name)
    model: Qwen3ForCausalLM = AutoModelForCausalLM.from_pretrained(model_name).to(device)
    optimizer = Adam(model.parameters(), lr=1e-4, betas=(0.9, 0.95))
    optimizer.zero_grad()
    model.train()

    train_seq = ["<think>\n\n</think>\n\n翻译：行我觉得如果我想要在前赶回宿舍的话，我就得尽快把事情做完。<|im_end|>"]
    inputs = tokenizer(train_seq, return_tensors="pt", padding=True).to(device)

    outputs = model(
        input_ids=inputs.input_ids,
        attention_mask=inputs.attention_mask,
        labels=inputs.input_ids
    )
    loss = outputs.loss
    loss.backward()
    optimizer.step()
    with torch.no_grad():
        model.eval()
        test_seq = "<|im_start|>user\n你好。<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
        inputs = tokenizer(test_seq, return_tensors="pt").to(device)
        output_ids = model.generate(**inputs, max_new_tokens=120)
```

将会出现如上的报错

其中 model_name = "../dl_models/Qwen3-0.6B" 是HF上拉取的最新模型

#### Expected results

正确运行，没有报错

#### Attempts to fix

以下几种方法均可使代码正常运行：

修改device = "cpu"
修改train_seq为其他语句，包括仅仅移除句中一个中文引号（“翻译”两字后）
移除  optimizer.step()
不修改，将上述代码移植到:
```python
RTX2070
CUDA Version: 12.9
torch==1.7.0+cu126
transformers==4.51.3
```

#### Anything else helpful for investigation

报错源于：

transformers\generation\utils.py line 3476:
next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
中 probs 均为nan

**Comment by O5-7** [comment]
我发现是训练中出现的梯度包含nan值导致的bug（包括嵌入层，qkv投影），不过尚不清楚是不是torch底层的问题，因为在CPU和不同GPU上出现了平台差异性。

但另一方面，修改训练输入文本就能让所有nan消失，把我搞不会了，所以我会保留这个issue，如果你们确定是torch的平台一致性问题，我会close

**Comment by jklj077** [comment]
Hi, 

```python
model: Qwen3ForCausalLM = AutoModelForCausalLM.from_pretrained(model_name).to(device)
```

In general, the above line should load the model with float32, which is unlikely to cause NaN (as a result of overflow). I didn't reproduce the issue with float32 and bfloat16/auto. But I reproduced this with float16, which is't rare in training LLMs. 

Could you try `print(next(model.lm_head.parameters()).dtype)` and see what precision the model was loaded with?

**Comment by O5-7** [comment]
Hi @jklj077 , the precision I used and the result of your code are all `torch.float32`, and I didn't use any amp or quantization

---

I am pretty sure that `torch.nn.functional.scaled_dot_product_attention`(SDPA) is causing this issue
I printed the std of Q and K during inference, and I get results as below:
```python
print(self.q_proj(hidden_states).std().item())  # before RMSNorm
print(self.k_proj(hidden_states).std().item())
print(self.q_norm(self.q_proj(hidden_states).view(hidden_shape)).std().item())  # after
print(self.k_norm(self.k_proj(hidden_states).view(hidden_shape)).std().item())
```
```
0.35983943939208984  # layer 0
0.3904779255390167
2.271184206008911
20.47869300842285

0.17101776599884033  # layer 1
0.19665756821632385
1.5322964191436768
10.916129112243652
...
```
As you can see the std of k is very large after RMSNorm (both CPU and GPU), Is this expected?

---

Then I tested the gradient changes in different parts

The number represents the input and output gradients of the module during backward
```
# layer 20
mlp                      1.9223785785928832e+24   4.114873695348224e+24
o_proj                   1.5806442859465054e+24   4.165737133366964e+24
attn_output              1.5806442859465054e+24
attn_output_in_sdpa      1.5806442859465054e+24  
query_in_sdpa            1.6337626588030862e+28  # 24 -> 28
value_in_sdpa            7.36131932082686e+26
key_in_sdpa              4.1153375571747013e+27
key_states               4.416244683427819e+27
query_states             1.6337626588030862e+28
value_states             7.362495485229e+26
v_proj                   5.0611911129272016e+26   7.362495485229e+26
k_norm                   2.7227639225556597e+27   4.416244683427819e+27
k_proj                   1.0961751877654439e+27   2.7227639225556597e+27
q_norm                   6.985321549981727e+27    1.6337604156790068e+28
q_proj                   4.669251665853569e+26    6.985321549981727e+27
input_layernorm          7.314184200369718e+26    1.1057529586494428e+27
layer                    7.302443216701683e+26    4.114873695348224e+24
```

As you can see, the gradient explode after SDPA

---

Finally, I reproduced this bug and post a issue in pytorch:

pytorch/pytorch/issues/156160

In short, long seq and unbalanced std cause gradient explosion in SDPA with CUDA on the RTX 5080.

Every time the backward through SDPA causes the gradients to increase by several orders of magnitude, eventually overflowing and resulting in inf.

**Comment by jklj077** [comment]
> the precision I used and the result of your code are all torch.float32

From past experience, this issue shouldn't occur with torch.float32. The model was trained using bfloat16, and float32 should be sufficiently precise for all computations.

> I am pretty sure that torch.nn.functional.scaled_dot_product_attention(SDPA) is causing this issue

PyTorch SDPA may select different implementations based on the inputs, data types, and devices. As you have tested, the same code worked on RTX 2070 (Turing) and I tested on A10 (Ampere), which also worked. It's likely that the implementation selected for the RTX 5080 (Blackwell) was causing the problem.

**Comment by O5-7** [comment]
This bug was fixed by upgrading cuDNN. Please use the preview version of PyTorch.
